name: flutter_demo01
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  english_words: ^4.0.0
  provider: ^6.0.0

  # 获取版本信息 https://pub.flutter-io.cn/packages/package_info_plus
  package_info_plus: ^5.0.1
  # 本地化存储 https://pub.flutter-io.cn/packages/shared_preferences
  shared_preferences: ^2.2.2
  # 并发锁 https://pub.flutter-io.cn/packages/synchronized
  synchronized: ^3.1.0+1
  # flustars很久不维护，可以使用这个替代 https://pub.flutter-io.cn/packages/flustars_flutter3
  flustars_flutter3: ^3.0.0
  # 加密 https://pub.flutter-io.cn/packages/encrypt
  encrypt: ^5.0.3
  # 使用国际化 https://pub-web.flutter-io.cn/packages/get
  get: ^4.6.6
  # 加载框 https://pub.flutter-io.cn/packages/bot_toast
  bot_toast: ^4.1.3
  # 路由管理 https://pub.flutter-io.cn/packages/fluro
  fluro: ^2.0.5
  # 动画 https://pub.flutter-io.cn/packages/animate_do
  animate_do: ^3.3.4
  # 图片缓存 https://pub.flutter-io.cn/packages/cached_network_image
  cached_network_image: ^3.3.1
  # 小红点 https://pub.flutter-io.cn/packages/badges
  badges: ^3.1.2
  # webview https://pub.flutter-io.cn/packages/webview_flutter
  webview_flutter: ^4.5.0
  # 图片库 https://pub.flutter-io.cn/packages/cupertino_icons
  cupertino_icons: ^1.0.6
  # 屏幕参数适配 https://pub.flutter-io.cn/packages/flutter_screenutil
  flutter_screenutil: ^5.9.0
  # 后退按钮拦截器 https://pub.flutter-io.cn/packages/back_button_interceptor
  back_button_interceptor: ^6.0.2
  # 监测网络状态 https://pub.flutter-io.cn/packages/connectivity_plus
  connectivity_plus: ^5.0.2
  # 网络请求 https://pub.flutter-io.cn/packages/dio
  dio: ^5.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/tab/
    - assets/images/common/
    - assets/images/common/empty/